### PR TITLE
Reload Jenkins CasC in Jenkins Config Controller

### LINKED ISSUE #73: Reload Jenkins CasC after setting pod resource limit of Jenkins agent
> ### Special notes for reviewers:
>
> There are two problems left here:
> 
> - After we change `jenkins-casc-config` configmap, we have to invoke reload Jenkins CasC configuration api. I suggest to make another pull request for this.
> - If users upgrade KubeSphere, we don't recognize whether `jenkins-casc-config` configmap is fresh or not. Similarly, I suggest to make another pull request for this one.

This issue comes from one of problems mentioned in the previous PR: <https://github.com/kubesphere-sigs/ks-devops/pull/26>. 

The main problem is that Jenkins will use old Jenkins CasC instead of new CasC updated by JenkinsConfigController, so that we cannot run Jenkins job correctly. please see the following error complained by Jenkins:

```java
2021-07-24 03:41:57.351+0000 [id=114] WARNING o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: base-77hd8, template=PodTemplate{id='4fb4d47b-486f-4797-af13-368e0fa16139', name='base', namespace='kubesphere-devops-worker', label='base', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock], HostPathVolume [mountPath=/root/.sonar/cache, hostPath=/var/data/jenkins_sonar_cache]], containers=[ContainerTemplate{name='base', image='kubespheredev/builder-base:v3.1.0', command='cat', args='', ttyEnabled=true, resourceRequestCpu='100m', resourceRequestMemory='100Mi', resourceLimitCpu='4000m', resourceLimitMemory='8192Mi'}, ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', command='jenkins-slave', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='50m', resourceRequestMemory='400Mi', resourceLimitCpu='500m', resourceLimitMemory='1536Mi'}]}

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/kubesphere-devops-worker/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. admission webhook "resourcesquotas.quota.kubesphere.io" denied the request: pods "base-77hd8" is forbidden: exceeded quota: worker-resource-quota, requested: limits.cpu=4500m,limits.memory=9728Mi, used: limits.cpu=0,limits.memory=0, limited: limits.cpu=3,limits.memory=3Gi.
```

/kind bug
/assign

### PR DESCRIPTION
**Pull request by JohnNiang**
### Which issue(s) this PR fixes

Fix #73

### Why we need it

Please see #73

### What this PR does

- Add `ConfigurationOperator` in DevOps client
- Reload configuration after reconciling Jenkins agent configuration
- Initial http client with no redirection for Jenkins client

### CODE REVIEW

**Comment by JohnNiang** [comment]
I've made some test cases for reloading Jenkins CasC.

- When Jenkins is down

```go
I0727 14:03:30.246707  774425 jenkinsconfig_controller.go:174] syncing key:kubesphere-devops-system/jenkins-agent-config
I0727 14:03:30.246813  774425 jenkinsconfig_controller.go:199] Jenkins agent pod resource limit: "default"
I0727 14:03:30.255078  774425 jenkinsconfig_controller.go:306] updated kubesphere-devops-worker/worker-resource-quota successfully
I0727 14:03:30.261809  774425 jenkinsconfig_controller.go:372] updated kubesphere-devops-worker/worker-limit-range successfully
I0727 14:03:30.278510  774425 jenkinsconfig_controller.go:456] updated configmap kubesphere-devops-system/jenkins-casc-config successfully
I0727 14:03:30.282080  774425 jenkinsconfig_controller.go:256] reloading devops configuration
I0727 14:03:30.283234  774425 jenkinsconfig_controller.go:259] synced key: kubesphere-devops-system/jenkins-agent-config
E0727 14:03:30.283333  774425 jenkinsconfig_controller.go:166] error syncing 'kubesphere-devops-system/jenkins-agent-config': Get "http://172.18.0.2:30180/crumbIssuer/api/json/api/json": read tcp 127.0.0.1:58962->127.0.0.1:1080: read: connection reset by peer, requeuing
```

- When Jenkins password/token is invalid

```go
I0727 14:06:16.477998  774425 jenkinsconfig_controller.go:174] syncing key:kubesphere-devops-system/jenkins-agent-config
I0727 14:06:16.478083  774425 jenkinsconfig_controller.go:199] Jenkins agent pod resource limit: "default"
I0727 14:06:16.487147  774425 jenkinsconfig_controller.go:306] updated kubesphere-devops-worker/worker-resource-quota successfully
I0727 14:06:16.491412  774425 jenkinsconfig_controller.go:372] updated kubesphere-devops-worker/worker-limit-range successfully
I0727 14:06:16.496267  774425 jenkinsconfig_controller.go:456] updated configmap kubesphere-devops-system/jenkins-casc-config successfully
I0727 14:06:16.497353  774425 jenkinsconfig_controller.go:256] reloading devops configuration
I0727 14:06:16.617020  774425 jenkinsconfig_controller.go:259] synced key: kubesphere-devops-system/jenkins-agent-config
E0727 14:06:16.617084  774425 jenkinsconfig_controller.go:166] error syncing 'kubesphere-devops-system/jenkins-agent-config': GET http://172.18.0.2:30180/crumbIssuer/api/json/api/json: 401 <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 Invalid password/token for user: admin</title>
</head>
<body><h2>HTTP ERROR 401 Invalid password/token for user: admin</h2>
<table>
<tr><th>URI:</th><td>/crumbIssuer/api/json/api/json</td></tr>
<tr><th>STATUS:</th><td>401</td></tr>
<tr><th>MESSAGE:</th><td>Invalid password/token for user: admin</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.30.v20200611</a><hr/>

</body>
</html>
, requeuing
```

- When `jenkinsconfigcontroller` reloads Jenkins CasC successfully

```go
I0727 14:49:57.551750  806527 jenkinsconfig_controller.go:174] syncing key:kubesphere-devops-system/jenkins-agent-config
I0727 14:49:57.551799  806527 jenkinsconfig_controller.go:199] Jenkins agent pod resource limit: "default"
I0727 14:49:57.551705  806527 shared_informer.go:253] caches populated
I0727 14:49:57.556888  806527 jenkinsconfig_controller.go:306] updated kubesphere-devops-worker/worker-resource-quota successfully
I0727 14:49:57.560267  806527 jenkinsconfig_controller.go:372] updated kubesphere-devops-worker/worker-limit-range successfully
I0727 14:49:57.567758  806527 jenkinsconfig_controller.go:456] updated configmap kubesphere-devops-system/jenkins-casc-config successfully
I0727 14:49:57.570040  806527 jenkinsconfig_controller.go:256] reloading devops configuration
I0727 14:49:59.943126  806527 jenkinsconfig_controller.go:261] reloaded devops configuration successfully
I0727 14:49:59.943157  806527 jenkinsconfig_controller.go:263] synced key: kubesphere-devops-system/jenkins-agent-config
I0727 14:49:59.943172  806527 jenkinsconfig_controller.go:161] successfully synced 'kubesphere-devops-system/jenkins-agent-config'
I0727 14:53:07.521910  806527 jenkinsconfig_controller.go:174] syncing key:kubesphere-devops-system/jenkins-agent-config
I0727 14:53:07.521935  806527 jenkinsconfig_controller.go:199] Jenkins agent pod resource limit: "high"
I0727 14:53:07.530210  806527 jenkinsconfig_controller.go:306] updated kubesphere-devops-worker/worker-resource-quota successfully
I0727 14:53:07.533961  806527 jenkinsconfig_controller.go:372] updated kubesphere-devops-worker/worker-limit-range successfully
I0727 14:53:07.545854  806527 jenkinsconfig_controller.go:456] updated configmap kubesphere-devops-system/jenkins-casc-config successfully
I0727 14:53:07.551854  806527 jenkinsconfig_controller.go:256] reloading devops configuration
I0727 14:53:08.777206  806527 jenkinsconfig_controller.go:261] reloaded devops configuration successfully
I0727 14:53:08.777228  806527 jenkinsconfig_controller.go:263] synced key: kubesphere-devops-system/jenkins-agent-config
I0727 14:53:08.777239  806527 jenkinsconfig_controller.go:161] successfully synced 'kubesphere-devops-system/jenkins-agent-config'
```

But there remains another problem that ConfigMap won't update immediately. In other words, when `jenkinsconfigcontroller` invoke Jenkins CasC reloading API, old Jenkins CasC will be applied.

**Comment by JohnNiang** [comment]
> But there remains another problem that ConfigMap won't update immediately. In other words, when jenkinsconfigcontroller invoke Jenkins CasC reloading API, old Jenkins CasC will be applied.

@LinuxSuRen , I would appreciate it if you could help me. Please see also [here](https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically).

File: controllers/jenkinsconfig/jenkinsconfig_controller.go [hunk 1]
```diff
@@ -246,6 +252,14 @@ func (c *Controller) syncHandler(key string) error {
 		return err
 	}
 
+	// Reload configuration
+	klog.V(5).Info("reloading devops configuration")
```
[the remark this answers is not in the document]
Comment (JohnNiang) [reply controllers/jenkinsconfig/jenkinsconfig_controller.go:256]: Alright.

File: controllers/jenkinsconfig/jenkinsconfig_controller.go [hunk 2]
```diff
@@ -246,6 +252,14 @@ func (c *Controller) syncHandler(key string) error {
...
+	err = c.configOperator.ReloadConfiguration()
+	if err != nil {
+		return err
```
[the remark this answers is not in the document]
Comment (JohnNiang) [reply controllers/jenkinsconfig/jenkinsconfig_controller.go:259]: The error will be printed by invoker(processNextWorkItem), please see the following codes:

https://github.com/kubesphere-sigs/ks-devops/blob/b5b741e3edcb517ebedc67dcbe00c1d5539a2fa0/controllers/jenkinsconfig/jenkinsconfig_controller.go#L156-L159

IMO, the error won't be hidden here.

**Comment by JohnNiang** [comment]
According to [KubeleteConfiguration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) we find that description of field "syncFrequencymeta":

> syncFrequency is the max period between synchronizing running containers and config. Dynamic Kubelet Config (beta): If dynamically updating this field, consider that shortening this duration may have a negative performance impact, especially as the number of Pods on the node increases. Alternatively, increasing this duration will result in longer refresh times for ConfigMaps and Secrets. Default: "1m"

That means ConfigMap will be refreshed in at most 1 minute by default.

There are some potential solutions I think:

1. Delayed 70s to invoke Jenkins CasC reloading API.
    - Pro
      Invode once after Jenkins CasC changes.
    - Con
      We cannot detect if ConfigMap is synced by Kubernetes. We may miss the latest Jenkins CasC.
2. Periodically invoke Jenkins CasC reloading API in daemon.
    - Pro
      This approach would guarantee the latest Jenkins CasC could be reloaded.
    - Con
      We have to keep a daemon process to invoke Jenkins CasC reloading API, and it reloads Jenkins CasC even if there is no Jenkins CasC change.

I'd prefer to `Delayed 70s to invoke Jenkins CasC reloading API` solution currently due to simplicity.

At last, what do you reckon for this question?

**Comment by LinuxSuRen** [comment]
> According to [KubeleteConfiguration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) we find that description of field "syncFrequencymeta":
> 
> > syncFrequency is the max period between synchronizing running containers and config. Dynamic Kubelet Config (beta): If dynamically updating this field, consider that shortening this duration may have a negative performance impact, especially as the number of Pods on the node increases. Alternatively, increasing this duration will result in longer refresh times for ConfigMaps and Secrets. Default: "1m"
> 
> That means ConfigMap will be refreshed in at most 1 minute by default.
> 
> There are some potential solutions I think:
> 
> 1. Delayed 70s to invoke Jenkins CasC reloading API.
>    
>    * Pro
>      Invode once after Jenkins CasC changes.
>    * Con
>      We cannot detect if ConfigMap is synced by Kubernetes. We may miss the latest Jenkins CasC.
> 2. Periodically invoke Jenkins CasC reloading API in daemon.
>    
>    * Pro
>      This approach would guarantee the latest Jenkins CasC could be reloaded.
>    * Con
>      We have to keep a daemon process to invoke Jenkins CasC reloading API, and it reloads Jenkins CasC even if there is no Jenkins CasC change.
> 
> I'd prefer to `Delayed 70s to invoke Jenkins CasC reloading API` solution currently due to simplicity.
> 
> At last, what do you reckon for this question?

solution 1 from me

But I prefer to make the delay time to be configurable. For example, add an option for the controller command line.

**Comment by JohnNiang** [comment]
After I added `ReloadCasCPeriod` option, `jenkinsconfigcontroller`'s process log is as follow:

```
I0727 16:58:33.047393  866726 jenkinsconfig_controller.go:178] syncing key:kubesphere-devops-system/jenkins-agent-config
I0727 16:58:33.047429  866726 jenkinsconfig_controller.go:203] Jenkins agent pod resource limit: "high"
I0727 16:58:33.051523  866726 jenkinsconfig_controller.go:314] updated kubesphere-devops-worker/worker-resource-quota successfully
I0727 16:58:33.055075  866726 jenkinsconfig_controller.go:380] updated kubesphere-devops-worker/worker-limit-range successfully
I0727 16:58:33.062754  866726 jenkinsconfig_controller.go:464] updated configmap kubesphere-devops-system/jenkins-casc-config successfully
I0727 16:58:33.064456  866726 jenkinsconfig_controller.go:260] waiting 1m10s to reload Jenkins configuration
I0727 16:59:43.065067  866726 jenkinsconfig_controller.go:264] reloading Jenkins configuration
I0727 16:59:43.065759  866726 jenkinsconfig_controller.go:267] synced key: kubesphere-devops-system/jenkins-agent-config
E0727 16:59:43.065815  866726 jenkinsconfig_controller.go:170] error syncing 'kubesphere-devops-system/jenkins-agent-config': Get "http://172.18.0.2:30180/crumbIssuer/api/json/api/json": read tcp 127.0.0.1:43544->127.0.0.1:1080: read: connection reset by peer, requeuing
I0727 16:59:43.226240  866726 jenkinsconfig_controller.go:178] syncing key:kubesphere-devops-system/jenkins-agent-config
I0727 16:59:43.226336  866726 jenkinsconfig_controller.go:203] Jenkins agent pod resource limit: "high"
I0727 16:59:43.230842  866726 jenkinsconfig_controller.go:314] updated kubesphere-devops-worker/worker-resource-quota successfully
I0727 16:59:43.234124  866726 jenkinsconfig_controller.go:380] updated kubesphere-devops-worker/worker-limit-range successfully
I0727 16:59:43.243075  866726 jenkinsconfig_controller.go:464] updated configmap kubesphere-devops-system/jenkins-casc-config successfully
I0727 16:59:43.245274  866726 jenkinsconfig_controller.go:260] waiting 1m10s to reload Jenkins configuration
I0727 17:00:53.245437  866726 jenkinsconfig_controller.go:264] reloading Jenkins configuration
I0727 17:00:55.137148  866726 jenkinsconfig_controller.go:269] reloaded Jenkins configuration successfully
I0727 17:00:55.137169  866726 jenkinsconfig_controller.go:271] synced key: kubesphere-devops-system/jenkins-agent-config
I0727 17:00:55.137180  866726 jenkinsconfig_controller.go:165] successfully synced 'kubesphere-devops-system/jenkins-agent-config'
```

File: pkg/client/devops/jenkins/options.go [hunk 3]
```diff
@@ -87,4 +93,7 @@ func (s *Options) AddFlags(fs *pflag.FlagSet, c *Options) {
 
 	fs.StringVar(&s.Namespace, "namespace", c.Namespace, "Namespace where devops system is in.")
 	fs.StringVar(&s.WorkerNamespace, "worker-namespace", c.WorkerNamespace, "Namespace where Jenkins agent workers are in.")
+	fs.DurationVar(&s.ReloadCasCPeriod, "reload-casc-period", c.ReloadCasCPeriod,
```
Comment (LinuxSuRen) [inline pkg/client/devops/jenkins/options.go:96]: `period` is incorrect. it should be `delay`.

File: pkg/client/devops/jenkins/options.go [hunk 4]
```diff
@@ -87,4 +93,7 @@ func (s *Options) AddFlags(fs *pflag.FlagSet, c *Options) {
...
+		"ReloadCasCPeriod specifies the total duration that controller should delay the reload action for "+
+			"jenkins-casc-config ConfigMap change, and it is only valid for controller manager. Default: \"70s\"")
```
Comment (LinuxSuRen) [inline pkg/client/devops/jenkins/options.go:98]: you don't need to provide the default value in the description. see also https://github.com/jenkins-zh/jenkins-cli/blob/c1846ac042deec330a39dd161679bacaf1386b3a/app/cmd/job_build.go#L41

let's assume, someone changes the default value. then he needs to change two places instead of one

**Comment by JohnNiang** [comment]
hi @LinuxSuRen , please take some time to have a look at new change for solution 1.

File: controllers/jenkinsconfig/jenkinsconfig_controller.go [hunk 5]
```diff
@@ -252,6 +256,10 @@ func (c *Controller) syncHandler(key string) error {
 		return err
 	}
 
+	// Wait some period to reload
+	klog.V(5).Infof("waiting %s to reload Jenkins configuration", c.ReloadCasCPeriod.String())
```
Comment (LinuxSuRen) [inline controllers/jenkinsconfig/jenkinsconfig_controller.go:260]: forget the unit of the time? minute? hour? or just second?

Comment (JohnNiang) [reply controllers/jenkinsconfig/jenkinsconfig_controller.go:260]: Please see the output [above comment](https://github.com/kubesphere-sigs/ks-devops/pull/75#issuecomment-887343523).

```go
waiting 1m10s to reload Jenkins configuration
```

Comment (LinuxSuRen) [reply controllers/jenkinsconfig/jenkinsconfig_controller.go:260]: got it.

File: pkg/client/devops/jenkins/options.go (hunk 4 above)
Comment (LinuxSuRen) [reply pkg/client/devops/jenkins/options.go:98]: lack of time unit description

File: pkg/client/devops/jenkins/options.go (hunk 3 above)
Comment (JohnNiang) [reply pkg/client/devops/jenkins/options.go:96]: My mistake. I misunderstand some fields related period in [Kubernetes type](https://github.com/kubernetes/kubelet/blob/c4c83cb3f378ed877f96f12d2e874d9a7888e521/config/v1beta1/types.go#L978-L983).

File: pkg/client/devops/jenkins/options.go (hunk 4 above)
Comment (JohnNiang) [reply pkg/client/devops/jenkins/options.go:98]: Alright.

Comment (JohnNiang) [reply pkg/client/devops/jenkins/options.go:98]: Option with duration type can be set to `1s`, `1m`, `1h`, or `1d`, so I think we can omit the time unit description.

Comment (LinuxSuRen) [reply pkg/client/devops/jenkins/options.go]: That's ok. But provide an example will be better. Such as

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

File: pkg/client/devops/jenkins/devops.go [hunk 6]
```diff
@@ -15,10 +15,17 @@ package jenkins
 
 import (
 	"kubesphere.io/devops/pkg/client/devops"
+	"net/http"
 )
 
 func NewDevopsClient(options *Options) (devops.Interface, error) {
-	jenkins := CreateJenkins(nil, options.Host, options.MaxConnections, options.Username, options.Password)
+	// we have to create http client with no redirection
```
Comment (LinuxSuRen) [inline pkg/client/devops/jenkins/devops.go:22]: I don't understand why we need to have the no redirection client.

Comment (JohnNiang) [reply pkg/client/devops/jenkins/devops.go:22]: If we make http request with POST method to some Jenkins endpoint, Jenkins will result in 302 back to http client, and http client will redirect to `Location`. If we don't specific `Referer` header, the http client will request same API using GET method again. That's not what we expected.
